version: '3.7'

services:
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_DATABASE: postgres
      DB_USERNAME: postgres
    command: ["make", "lint", "test-coverage"]

  db:
    image: postgres:14.4-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
