name: Main

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: satackey/action-docker-layer-caching@v0.0.11
      # Здесь проект завёрнут в docker, но это не обязательно
      # Могут быть и прямые вызовы make setup, make lint и т.д.
      - name: Run CI
        run: |
          make ci

      - name: Publish code coverage
        uses: codecov/codecov-action@v1
        with:
          file: build/logs/clover.xml
          fail_ci_if_error: true
          verbose: true
